apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-apache
spec:
  selector:
    matchLabels:
      run: httpd-apache
  template:
    metadata:
      name: pod-httpd
      labels:
        run: httpd-apache
    spec:
      containers:
        - name: httpd-apache
          image: hisbu/test-php
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m    

---

apiVersion: v1
kind: Service
metadata:
  name: svc-httpd
  labels:
    run: httpd-apache
spec:
  type: NodePort
  selector:
    run: httpd-apache
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30012

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-httpd
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpd-apache
  metrics:
    - type: Resource 
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 45